version: "3.7"
services:
  spark-solo:
    image: pcontop/spark-cli:first
    command: tail -F anything
    networks:
      - webnet

  cassandra:
    image: cassandra:3.0
    ports:
      - "9160:9160"
      - "9042:9042"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

networks:
  webnet: